version: '2'
services:
    myfitbandweb-app:
        image: myfitbandweb
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://myfitbandweb-mysql:3306/myfitbandweb?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    myfitbandweb-mysql:
        extends:
            file: mysql.yml
            service: myfitbandweb-mysql
